version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lms-postgres
    environment:
      POSTGRES_DB: lms_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lms-network

  redis:
    image: redis:7-alpine
    container_name: lms-redis
    ports:
      - "6379:6379"
    networks:
      - lms-network

  minio:
    image: minio/minio:latest
    container_name: lms-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lms-network

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: lms-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - lms-network

volumes:
  postgres_data:
  minio_data:

networks:
  lms-network:
    driver: bridge